export const pipelineConfig = {
  files: {
    rawTopics: 'raw_topics.json',
    scoredTopics: 'scored_topics.json',
    postsQueue: 'posts_queue.json',
    imageManifest: 'image_manifest.json',
    contentManifest: 'content_manifest.json',
    weeklyPlan: 'weekly_plan.json',
    imagesDir: 'generated_images',
    facebookContextReport: 'facebook_context_checks.json',
    facebookDiagnosticsDir: 'facebook_context_diagnostics',
    logsDir: 'logs',
    database: 'howto-content.sqlite',
    backupsDir: 'backups',
  },
  browser: {
    headless: false,
    viewport: { width: 1400, height: 900 },
    userDataDir: process.env.CONTENT_RESEARCH_USER_DATA_DIR || null,
    pauseForManualLogin: process.env.CONTENT_RESEARCH_SKIP_LOGIN_PAUSE !== '1',
    loginWaitMs: readPositiveInteger(process.env.CONTENT_RESEARCH_LOGIN_WAIT_MS, 0),
  },
  scraper: {
    redditPostsPerSubreddit: 20,
    redditMinUpvotesPrimary: 100,
    redditMinUpvotesBackup: 100,
    redditMinItemsBeforeBackup: 40,
    redditMaxItemsPerNiche: 70,
    googleTrendsGeo: 'US',
    googleTrendsDate: 'now 7-d',
    googleTrendsItemsPerSeed: 25,
    googleTrendsMaxItemsPerNiche: 50,
    googleTrendsMinRisingBeforeTop: 5,
    googleTrendsRenderTimeoutMs: 15000,
    googleTrendsDelayMinMs: 2000,
    googleTrendsDelayMaxMs: 3000,
    pinterestAutocompletePerTerm: 12,
    pinterestPinsPerTerm: 40,
    pinterestMinPinTitlesPerTerm: 20,
    pinterestDelayMinMs: 1500,
    pinterestDelayMaxMs: 2500,
    pinterestDelayBetweenNichesMs: 4000,
    youtubeUseFreshContext: true,
    youtubeSuggestionsPerSeed: 12,
    youtubeTypeDelayMs: 60,
    youtubeSuggestionTimeoutMs: 8000,
    youtubePostTypeSettleMs: 1200,
    youtubeDebugOnZero: true,
    youtubeDelayMinMs: 800,
    youtubeDelayMaxMs: 1200,
    youtubeDelayBetweenNichesMs: 2000,
    quoraItemsPerPull: 15,
    quoraWaitForSelectorMs: 12000,
    quoraDelayBetweenPullsMs: 3000,
    quoraDelayBetweenNichesMs: 5000,
    quoraCooldownEveryNiches: 2,
    quoraCooldownMs: 10000,
    quoraTopicScrollY: 2000,
    quoraTopicSettleMs: 2500,
    quoraSearchScrollY: 1500,
    quoraSearchSettleMs: 2000,
    sourceTimeoutMs: 30000,
    settleMs: 2500,
  },
  scorer: {
    model: 'claude-sonnet-4-6',
    maxTokens: 6000,
    temperature: 0.35,
    delayBetweenNichesMs: 1500,
    outputItemsPerNiche: 30,
  },
  image: {
    provider: 'higgsfield',
    model: 'nano-banana',
    aspectRatio: '1:1',
    promptStyle: 'realistic social post image, no text overlay, no watermark, natural lighting',
    higgsfieldLoginWaitMs: readPositiveInteger(process.env.CONTENT_RESEARCH_HIGGSFIELD_LOGIN_WAIT_MS, 0),
    higgsfieldProjectDir: '_higgsfield/project',
  },
  visualDedup: {
    enabled: true,
    sameNicheThreshold: 0.64,
    globalThreshold: 0.74,
    recentLimit: 80,
    statuses: ['scheduled', 'scheduling', 'qa_done', 'content_done', 'image_done', 'image_generating'],
  },
  content: {
    model: 'claude-sonnet-4-6',
    maxTokens: 1800,
    temperature: 0.35,
    delayBetweenPostsMs: 1200,
    minCaptionChars: 450,
    maxCaptionChars: 1800,
    minStepCount: 3,
  },
  qa: {
    model: 'claude-sonnet-4-6',
    maxTokens: 1400,
    temperature: 0.1,
    minPassScore: 75,
    minImageBytes: 50000,
    minImageWidth: 700,
    minImageHeight: 700,
    maxAspectSkew: 0.35,
    delayBetweenPostsMs: 1000,
  },
  dedup: {
    hardSimilarityThreshold: 0.78,
    softSimilarityThreshold: 0.62,
    minTokenCount: 2,
    hardStatuses: ['scheduled', 'published'],
    softStatuses: ['scheduled', 'published', 'qa_done', 'content_done', 'scheduling'],
  },
  weekly: {
    days: 7,
    postsPerPage: 7,
    scheduleLeadDays: 1,
    startTime: '15:00',
    slotIntervalMinutes: 60,
    eligibleStatuses: ['queued'],
    activeCalendarStatuses: ['scheduled', 'scheduling', 'qa_done', 'content_done'],
    skipPagesWithActivePost: true,
    activePageStatuses: [
      'approved',
      'image_generating',
      'image_done',
      'content_generating',
      'content_done',
      'qa_generating',
      'qa_done',
      'scheduling',
      'scheduled',
    ],
  },
  facebook: {
    homeUrl: 'https://www.facebook.com/',
    contentLibraryUrl: 'https://www.facebook.com/professional_dashboard/content/content_library/',
    loginWaitMs: readPositiveInteger(process.env.CONTENT_RESEARCH_FACEBOOK_LOGIN_WAIT_MS, 0),
    pageSwitchTimeoutMs: 30000,
    dashboardTimeoutMs: 30000,
    settleMs: 2500,
    contextFreshHours: readPositiveInteger(process.env.CONTENT_RESEARCH_FACEBOOK_CONTEXT_FRESH_HOURS, 24),
    defaultScheduleLeadDays: readPositiveInteger(process.env.CONTENT_RESEARCH_FACEBOOK_SCHEDULE_LEAD_DAYS, 1),
    defaultScheduleTime: process.env.CONTENT_RESEARCH_FACEBOOK_SCHEDULE_TIME || '15:00',
  },
  niches: [
    {
      id: 'fix-it',
      name: 'How to Fix It',
      facebook_page_name: 'Fix It',
      reddit: {
        primary: ['DIY', 'HomeImprovement', 'fixit'],
        backup: ['HomeRepair', 'handyman'],
      },
      pinterest_terms: ['how to fix', 'home repair hacks', 'DIY repairs'],
      youtube_seeds: ['how to fix', 'how to repair', 'DIY how to'],
      google_trends_keywords: ['how to fix', 'home repair'],
      quora_topics: ['Home-Repair', 'DIY-Projects'],
      quora_search_terms: ['how to fix at home', 'home repair tips'],
    },
    {
      id: 'cook-it',
      name: 'How to Cook It',
      facebook_page_name: 'Cook It',
      reddit: {
        primary: ['Cooking', 'EatCheapAndHealthy', 'MealPrepSunday'],
        backup: ['recipes', 'Baking'],
      },
      pinterest_terms: ['how to cook', 'easy dinner recipes', 'quick meals'],
      youtube_seeds: ['how to cook', 'how to make', 'easy recipe'],
      google_trends_keywords: ['how to cook', 'easy recipe'],
      quora_topics: ['Cooking', 'Recipes'],
      quora_search_terms: ['how to cook', 'easy cooking tips'],
    },
    {
      id: 'grow-it',
      name: 'How to Grow It',
      facebook_page_name: 'Grow It',
      reddit: {
        primary: ['gardening', 'vegetablegardening', 'homesteading'],
        backup: ['IndoorGarden', 'composting'],
      },
      pinterest_terms: ['how to grow vegetables', 'garden tips', 'indoor plants'],
      youtube_seeds: ['how to grow', 'how to plant', 'gardening how to'],
      google_trends_keywords: ['how to grow', 'gardening tips'],
      quora_topics: ['Gardening', 'Indoor-Plants'],
      quora_search_terms: ['how to grow plants', 'gardening beginners'],
    },
    {
      id: 'money',
      name: 'How to Make Money',
      facebook_page_name: 'Money it',
      reddit: {
        primary: ['personalfinance', 'Frugal', 'sidehustle'],
        backup: ['passive_income', 'beermoney'],
      },
      pinterest_terms: ['how to save money', 'side hustle ideas', 'money tips'],
      youtube_seeds: ['how to make money', 'how to save money', 'side hustle'],
      google_trends_keywords: ['how to make money', 'side hustle'],
      quora_topics: ['Personal-Finance', 'Making-Money'],
      quora_search_terms: ['how to make money', 'save money tips'],
    },
    {
      id: 'get-fit',
      name: 'How to Get Fit',
      facebook_page_name: 'Get Fit',
      reddit: {
        primary: ['fitness', 'bodyweightfitness', 'loseit'],
        backup: ['xxfitness', 'running'],
      },
      pinterest_terms: ['home workout', 'how to lose weight', 'fitness tips'],
      youtube_seeds: ['how to lose weight', 'how to build muscle', 'home workout'],
      google_trends_keywords: ['how to lose weight', 'home workout'],
      quora_topics: ['Fitness', 'Weight-Loss'],
      quora_search_terms: ['how to lose weight', 'home workout tips'],
    },
    {
      id: 'make-it',
      name: 'How to Make It',
      facebook_page_name: 'Make It',
      reddit: {
        primary: ['crafts', 'DIY', 'upcycling'],
        backup: ['sewing', 'woodworking'],
      },
      pinterest_terms: ['DIY crafts', 'how to make', 'upcycle ideas'],
      youtube_seeds: ['how to make', 'how to build', 'DIY how to make'],
      google_trends_keywords: ['how to make', 'DIY craft'],
      quora_topics: ['DIY-Projects', 'Arts-and-Crafts'],
      quora_search_terms: ['how to make DIY', 'craft ideas home'],
    },
    {
      id: 'tech-it',
      name: 'How to Tech It',
      facebook_page_name: 'Tech It',
      reddit: {
        primary: ['technology', 'ChatGPT', 'artificial'],
        backup: ['productivity', 'lifehacks'],
      },
      pinterest_terms: ['phone hacks', 'AI tools', 'productivity tips'],
      youtube_seeds: ['how to use', 'how to set up', 'ChatGPT how to'],
      google_trends_keywords: ['how to use AI', 'ChatGPT tips'],
      quora_topics: ['Technology', 'Artificial-Intelligence'],
      quora_search_terms: ['how to use AI tools', 'tech tips beginners'],
    },
    {
      id: 'look-good',
      name: 'How to Look Good',
      facebook_page_name: 'Look Good',
      reddit: {
        primary: ['SkincareAddiction', 'malefashionadvice', 'femalefashionadvice'],
        backup: ['beauty', 'Frugal'],
      },
      pinterest_terms: ['skincare routine', 'how to style outfits', 'grooming tips'],
      youtube_seeds: ['how to style', 'how to do skincare', 'how to'],
      google_trends_keywords: ['how to style', 'skincare routine'],
      quora_topics: ['Skin-Care', 'Fashion-and-Style'],
      quora_search_terms: ['skincare routine tips', 'how to dress better'],
    },
  ],
};

function readPositiveInteger(value, fallback) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed) || parsed < 0) return fallback;
  return Math.round(parsed);
}
